## Student Performance Prediction

In [5]:
#importing libraries pandas and numpy for dataframe manipulation sklearn for regression model

import pandas as pd
import numpy as np
import sklearn
from sklearn import linear_model

In [6]:
#read data from the csv file (Dataset link in Read-me file)

data=pd.read_csv(r"C:\Users\Sameer.Joshi\Downloads\student\student-mat.csv",sep=";")

#choosing only those attributes which will be affecting the student performance
data=data[['studytime','failures','absences','G1','G2','G3']]
data.head()

   studytime  failures  absences  G1  G2  G3
0          2         0         6   5   6   6
1          2         0         4   5   5   6
2          2         3        10   7   8  10
3          3         0         2  15  14  15
4          2         0         4   6  10  10

In [9]:

#Regression model : data split => create model => finding accuracy from test data

X=np.array(data.drop(['G3'],1))
X
y=np.array(data['G3'])
y

x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, test_size=0.1)

linear=linear_model.LinearRegression()
linear.fit(x_train,y_train)
acc=linear.score(x_test,y_test)
print("Accuracy: \n",acc)
print("Coefficient: \n",linear.coef_)
print('Intercept: \n',linear.intercept_)
predictions=linear.predict(x_test)

Accuracy:
 0.9433896227988029
Coefficient:
 [-0.15281308 -0.29103287  0.04582639  0.14163171  0.99089879]
Intercept:
 -1.6219168100700738

In [10]:
#Create table to see comparison between o/p and expected o/p

ip_list=[]
op_list=[]
ex_list=[]
for i in range(0,len(x_test)):
    ip_list.append(x_test[i])
    op_list.append(predictions[i])
    ex_list.append(y_test[i])
    
compare={'Input':ip_list,'Output':op_list,'Expected o/p':ex_list}
compare_df=pd.DataFrame.from_dict(compare)
compare_df.head(10)

                Input     Output  Expected o/p
0  [1, 0, 20, 13, 12]  12.873796            12
1   [3, 0, 0, 15, 15]  14.907601            15
2     [3, 0, 0, 7, 0]  -1.088934             0
3   [1, 0, 4, 14, 14]  14.264003            14
4     [2, 0, 0, 9, 0]  -0.652858             0
5   [1, 1, 6, 12, 13]  12.790460            14
6     [2, 3, 5, 7, 7]   5.356204             7
7   [1, 0, 2, 17, 15]  15.588144            15
8   [2, 0, 2, 10, 10]   9.489415            11
9  [2, 1, 18, 12, 10]  10.214868            10